apps/informesContables/urls.py
from __future__ import unicode_literals
from __future__ import absolute_import
from django.conf.urls import url
from apps.informesContables.views import *
from django.contrib.auth.views import LogoutView
app_name='informes'
urlpatterns=[
url(r'^principal/', inicio,name="indexp"),
url(r'^indexInformes/', indexin,name="indexinf"),
url(r'^balancecomp/(?P<ini>\w+)/(?P<fin>\w+)', comprobacion,name="balCo"),
url(r'^balancegener/(?P<ini>\w+)/(?P<fin>\w+)', general,name="balG"),
url(r'^cambiospatrimonio/(?P<ini>\w+)/(?P<fin>\w+)', patrimonio,name="CambPa"),
url(r'^estadresultados/(?P<ini>\w+)/(?P<fin>\w+)', resultado,name="res"),
url(r'^librodiario/(?P<ini>\w+)/(?P<fin>\w+)', librodia,name="dia"),
]

apps/ingreso/urls.py
from __future__ import unicode_literals
from __future__ import absolute_import
from django.conf.urls import url
from apps.ingreso.views import *
from django.contrib.auth.views import LogoutView
app_name='ingreso'
urlpatterns=[
url(r'^login/', auth, name="ingresar"),
url(r'^index/', index,name="index"),
url(r'^logout', LogoutView.as_view(next_page='/ingreso/login'), name="logout"),
]

sic/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ingreso/', include('apps.ingreso.urls')),
    path('informes/', include('apps.informesContables.urls')),
    path('cuenta/', include('apps.registroCuentas.urls')),
    path('inventario/', include('apps.inventario.urls')),
]

templates/base/base.html
{% load static%}
<!DOCTYPE html>
<html>
<head>
	<title>Sistemas Contables 2019</title>
	{%block CSS%}
	<link rel="stylesheet" type="text/css" href="{% static "css/menu.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "css.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "js/scriptA.js" %}">
	{%endblock CSS%}
	
</head>
<body>
{%block logout%}

<div id="header">
			<ul class="nav">
				<li><a href="{%  url 'informes:indexinf'%}">Inicio</a></li>
				<li><a href="{% url 'index_principal' %}">Gestionar Cuentas</a></li>
				<li><a href="{%  url 'index_transaccion'%}">Gestionar Transacciones</a></li>
				<li><a href="{%  url 'index_inventario'%}">Inventario</a></li>
				<li><a href="{%  url 'ingreso:logout'%}">Salir</a></li>
			</ul>
		</div>
<hr>
{%endblock logout%}
{%block navegacion%}
{%endblock navegacion%}

{%block contenido%}
{%endblock contenido%}

</body>
</html>